default: &default
  adapter: mysql2
  pool: 5
  timeout: 30000
  encoding: utf8
  host: <%= ENV.fetch('MYSQL_HOST', 'localhost') %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "") %>

development:
  <<: *default
  database: gnnomethelabors_development

test:
  <<: *default
  database: gnnomethelabors_test

production:
  <<: *default
  database: gnnomethelabors_production